const actionTypes = {
  REPLACE_USER: 'REPLACE_USER',
  CLEAR_USER: 'CLEAR_USER',

  REPLACE_STORE_LIST: 'REPLACE_STORE_LIST',
  CLEAR_STORE_LIST: 'CLEAR_STORE_LIST',

  REPLACE_CURSTORE: 'REPLACE_CURSTORE',
  CLEAR_CURSTORE: 'CLEAR_CURSTORE',

  REPLACE_ADS: 'REPLACE_ADS',
  CLEAR_ADS: 'CLEAR_ADS',
  REPLACE_AVAIL_BALANCE: 'REPLACE_AVAIL_BALANCE',
  CLEAR_AVAIL_BALANCE: 'CLEAR_AVAIL_BALANCE',
  REPLACE_COUPONS: 'REPLACE_COUPONS',
  CLEAR_COUPONS: 'CLEAR_COUPONS',
  REPLACE_TRANS_HISTORY: 'REPLACE_TRANS_HISTORY',
  CLEAR_TRANS_HISTORY: 'CLEAR_TRANS_HISTORY',
  REPLACE_NOTIFICATIONS: 'REPLACE_NOTIFICATIONS',
  CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS',

  REPLACE_STATUS: 'REPLACE_STATUS',
};

export default actionTypes;
