const actionTypes = {
  // user
  REPLACE_USER: 'REPLACE_USER',
  CLEAR_USER: 'CLEAR_USER',

  REPLACE_USER_ACCOUNT: 'REPLACE_USER_ACCOUNT',
  REPLACE_USER_PASSWORD: 'REPLACE_USER_PASSWORD',
  REPLACE_USER_TRANSPWD: 'REPLACE_USER_TRANSPWD',
  REPLACE_USER_NAME: 'REPLACE_USER_NAME',

  // stores
  REPLACE_STORES: 'REPLACE_STORES',
  CLEAR_STORES: 'CLEAR_STORES',

  // wallets
  REPLACE_WALLETS: 'REPLACE_WALLETS',
  CLEAR_WALLETS: 'CLEAR_WALLETS',

  // curstore
  REPLACE_CURSTORE: 'REPLACE_CURSTORE',
  CLEAR_CURSTORE: 'CLEAR_CURSTORE',
  REPLACE_ADS: 'REPLACE_ADS',
  CLEAR_ADS: 'CLEAR_ADS',
  REPLACE_COUPONS: 'REPLACE_COUPONS',
  CLEAR_COUPONS: 'CLEAR_COUPONS',

  // notifications
  REPLACE_NOTIFICATIONS: 'REPLACE_NOTIFICATIONS',
  CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS',

  // curwallet
  REPLACE_CURWALLET: 'REPLACE_CURWALLET',
  CLEAR_CURWALLET: 'CLEAR_CURWALLET',
  REPLACE_AVAIL_BALANCE: 'REPLACE_AVAIL_BALANCE',
  CLEAR_AVAIL_BALANCE: 'CLEAR_AVAIL_BALANCE',
  REPLACE_TRANS_HISTORY: 'REPLACE_TRANS_HISTORY',
  CLEAR_TRANS_HISTORY: 'CLEAR_TRANS_HISTORY',

  // status
  REPLACE_STATUS: 'REPLACE_STATUS',
};

export default actionTypes;
